language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install: pip install .

script: python -m unittest

deploy:
  provider: pypi
  user: PPACI
  password: $PYPI_PWD
  skip_existing: true
  on:
    tags: true